require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/customer_orders", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CustomerOrder. As you add validations to CustomerOrder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CustomerOrder.create! valid_attributes
      get customer_orders_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      customer_order = CustomerOrder.create! valid_attributes
      get customer_order_url(customer_order)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_customer_order_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      customer_order = CustomerOrder.create! valid_attributes
      get edit_customer_order_url(customer_order)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CustomerOrder" do
        expect {
          post customer_orders_url, params: { customer_order: valid_attributes }
        }.to change(CustomerOrder, :count).by(1)
      end

      it "redirects to the created customer_order" do
        post customer_orders_url, params: { customer_order: valid_attributes }
        expect(response).to redirect_to(customer_order_url(CustomerOrder.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CustomerOrder" do
        expect {
          post customer_orders_url, params: { customer_order: invalid_attributes }
        }.to change(CustomerOrder, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post customer_orders_url, params: { customer_order: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested customer_order" do
        customer_order = CustomerOrder.create! valid_attributes
        patch customer_order_url(customer_order), params: { customer_order: new_attributes }
        customer_order.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the customer_order" do
        customer_order = CustomerOrder.create! valid_attributes
        patch customer_order_url(customer_order), params: { customer_order: new_attributes }
        customer_order.reload
        expect(response).to redirect_to(customer_order_url(customer_order))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        customer_order = CustomerOrder.create! valid_attributes
        patch customer_order_url(customer_order), params: { customer_order: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested customer_order" do
      customer_order = CustomerOrder.create! valid_attributes
      expect {
        delete customer_order_url(customer_order)
      }.to change(CustomerOrder, :count).by(-1)
    end

    it "redirects to the customer_orders list" do
      customer_order = CustomerOrder.create! valid_attributes
      delete customer_order_url(customer_order)
      expect(response).to redirect_to(customer_orders_url)
    end
  end
end
